before_install:
  # workaround https://github.com/travis-ci/travis-ci/issues/4629
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
language: java
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
#    - os: osx
#      env: JAVA_HOME=$(/usr/libexec/java_home)
