#
# MIT License
#
# Copyright (c) 2010 - 2020 The OSHI Project Contributors: https://github.com/oshi/oshi/graphs/contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: Synchornize Coverity branch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # daily at 09:00 UTC

jobs:
  build:
    if: github.repository_owner == 'oshi'
    runs-on: ubuntu-latest
    name: Synchornize Coverity Scan branch
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11          
      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_TOKEN&project=dblock%2Foshi" -O coverity_tool.tgz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}          
          
      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-configure --comptype gcc --compiler gcc-4.8 --template
          cov-build --dir cov-int ./mvnw -B -DskipTests=true clean compile
          tar czvf oshi.tgz cov-int
          curl --form token=$COVERITY_TOKEN \
            --form email=$EMAIL \
            --form file=@oshi.tgz \
            --form version="oshi/coverity_scan" \
            --form description="Oshi Coverity Scan" \
            https://scan.coverity.com/builds?project=dblock%2Foshi
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
